name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Get next version
        uses: thenativeweb/get-next-version@main
        id: get_next_version

      - name: Update package.json with new version
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          NEXT_VERSION="${{ steps.get_next_version.outputs.version }}"
          npm version $NEXT_VERSION --no-git-tag-version --allow-same-version
          git config --global user.email "lonoxx96@gmail.com"
          git config --global user.name "LonoxX"
          git add .
          git commit -m "chore: update version to ${NEXT_VERSION}"
          git push origin main
      - name: Create New Release
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          NEXT_VERSION="${{ steps.get_next_version.outputs.version }}"
          git tag $NEXT_VERSION
          git push origin $NEXT_VERSION
